### ISSUE TITLE
Contact “Calling Purgatory from Heaven: Binding to Rust in Haskell” author

### ISSUE THREAD

**Issue by haroldcarr** [yvan-sraka/hs-bindgen#1]
I notice no commits in a couple of months.

And now I see:

[the Well-Typed haskell/rust work](https://well-typed.com/blog/2023/03/purgatory/)

**Comment by yvan-sraka** [comment]
Hi Harold,

Thank you for your interest in this project once again. I can confirm that IOG considers this project to have achieved meeting the current company's requirements. Then, I got assigned me other priorities to work on for now. However, I am still maintaining the project in my free time and plan to release a new version soon with a few adjustments. I will push my work-in-progress PRs this weekend.

I have not yet had the time to delve deeply into [the blog post from Well-Typed](https://well-typed.com/blog/2023/03/purgatory/), but it may be worth investigating to see if there are any insights or techniques that could benefit `hs-bindgen`. Additionally, I may have already mentioned that there is a draft blog post in preparation that focuses on the Rust internals and advanced usage examples and design considerations of `hs-bindgen`. I hope this post will make it to the IOG engineering blog in the near future, but in any case, I can give you a sneak peek if you are curious!

Thank you for your continued interest in this project. Please let me know if you have any other questions or concerns.

Best, Yvan

**Comment by haroldcarr** [comment]
Thank you for you response and the project.  I am looking forward to your blog post.

**Comment by yvan-sraka** [comment]
I've taken the liberty of changing the title of this issue. After [discussing the matter on Mastodon](https://functional.cafe/@yvan/110324094269276826), I've opened two new issues:

- https://github.com/yvan-sraka/hs-bindgen/issues/3
- https://github.com/yvan-sraka/cargo-cabal/issues/6
