### ISSUE TITLE
How do I send / receive Rust structs in Haskell?

### ISSUE THREAD

**Issue by thiskappaisgrey** [yvan-sraka/hs-bindgen#10]
Hello, I just wanted to know if there is an example for sending / receiving Rust structs from/to Haskell, i.e.:
```
struct A {
    x: u64,
    y: String,
}

#[hs_bindgen(hello ::  IO (A))]
fn hello() {
    let a = A {
        x: 3301,
        y: "liber primus".to_string(),
    };
    return a;
}
```

I'm not super familiar with the haskell / rust FFI, but to my understanding, the Rust struct would need to be encoded as a stream of bits (i.e. `Vec<u8>`) and decoded on the Haskell side. I also looked at: https://well-typed.com/blog/2023/03/purgatory/#bounded-size-data - and they were using https://borsh.io/ as an encoding / decoding binary format - but the packages mentioned in that blog seems complicated and a bit manual to use than this package. 

I also tried to use: https://borsh.io/ (mentioned in article) by serializing the `A` struct in the Rust side and sending it to Haskell as a CString (which is probably "wrong"), but I couldn't get the deserialization to work in the haskell side. I think the "proper" way to do this (like in the other article) is to allocate a buffer (like a `Vec<u8>` in Rust) with a known size from Haskell, and fill that buffer with the encoded values, then decode them in Haskell, but I don't really know how to do this yet..

**Comment by thiskappaisgrey** [comment]
Ok, I managed to get a small example working here: https://github.com/thiskappaisgrey/hs-bindgen-struct-example/tree/main 

This function sends a Rust struct to Haskell: https://github.com/thiskappaisgrey/hs-bindgen-struct-example/blob/main/greetings/src/lib.rs#L30

And this function recieves the data: https://github.com/thiskappaisgrey/hs-bindgen-struct-example/blob/main/test/app/Main.hs#L47

And there might be other ways to serialize the data and such as well? I found: https://github.com/getditto/safer_ffi while looking at: https://users.rust-lang.org/t/pass-a-vec-from-rust-to-c/59184 (to find ways of passing a Rust Vector to C). I think the Haskell code, right now, needs to manually call a deallocator from Rust once it's done with the vector in order to not memory leak.

**Comment by haroldcarr** [comment]
Take a look at this article for another way to bind Haskell to Rust:
https://well-typed.com/blog/2023/03/purgatory/
Even if you don't use it, it is a good tutorial on things one needs to do when interoperating with Rust (including getting the Haskell GC to call Rust deallocators).

**Comment by yvan-sraka** [comment]
Hi, @thiskappaisgrey, as @haroldcarr mentioned and as you've already figured out in your issue description, there is a [blog post from Well-Typed](https://well-typed.com/blog/2023/03/purgatory/) suggesting https://borsh.io/ among many other serialization methods that could be used. I believe the idea is that it's not the role of this library to enforce a specific serialization method. However, I think it would be helpful to have a better example on how to do that in the README. If you agree, I will adapt and include your code snippet, making it properly calls a custom Rust deallocator. Thanks again for experimenting with `hs-bindgen`! :)

**Comment by thiskappaisgrey** [comment]
@yvan-sraka - That would be awesome! Please feel free to adapt my code snippet. Thanks for making `hs-bindgen`! Would love to be able to see more bindings from Rust to Haskell.
