### ISSUE TITLE
Indicating `safe` or `unsafe` in generated haskell ffi

### ISSUE THREAD

**Issue by Eisverygoodletter** [yvan-sraka/hs-bindgen#8]
How do I indicate whether the generated haskell (ffi) function should have `safe` or `unsafe`?

I saw the code here https://github.com/yvan-sraka/hs-bindgen-attribute/blob/5cf763149a5af1d1072201ae2af570e60caf3da4/src/haskell.rs#L19-L24
but I'm not sure how `Signature`s are parsed, so how do I control `sig.fn_safe`?

**Comment by yvan-sraka** [comment]
Hi @Eisverygoodletter,

Thanks for asking this question, and sorry for having it undocumented ... the answer can be found in [the IOG's engineering blog post introducing these tools](https://engineering.iog.io/2023-01-26-hs-bindgen-introduction):

> Thanks to community feedbacks from Merijn Verstraaten, I just released hs-bindgen v0.8.0 that now generates `safe` Haskell foreign imports by default! You can still generate `unsafe` bindings simply by prefixing a function name like `#[hs_bindgen(unsafe NAME :: TYPE)]` in Rust attribute macro. I invite you to read [“FFI safety and GC”](https://frasertweedale.github.io/blog-fp/posts/2022-09-23-ffi-safety-and-gc.html) by Fraser Tweedale or GHC's users guide to understand the differences between Haskell `unsafe`/`safe` keywords.

**Comment by Eisverygoodletter** [comment]
Thanks for the explanation.
